apiVersion: v1
kind: Service
metadata:
  name: techtaurant-be-debug-nodeport
  namespace: be-dev
  labels:
    app.kubernetes.io/name: techtaurant-be
    app.kubernetes.io/instance: be-dev
    app.kubernetes.io/component: debug-access
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: techtaurant-be
    app.kubernetes.io/instance: be-dev
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
      nodePort: 30880
