apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: be-dev
resources:
  - deployment.yaml
  - service.yaml
  - debug-nodeport.yaml
images:
  - name: ghcr.io/techtaurant/be-k8s-poc
    newTag: dev-initial
