apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.com
spec:
  project: techtaurant
  source:
    repoURL: https://github.com/Techtaurant/gitops.git
    targetRevision: HEAD
    path: apps/database/redis/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-prod
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
