---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis-dev
spec:
  encryptedData:
    password: AgB2cDUbMFvLSUTn0wE+F4FuAlyxv6lRuU81SGx4bUM9nC1rQ8uGLahrQZtFvfkdoP2ugDH0mY0Nd01i2hFv7g4jIeo5OgLUJel0xVZbSeXv6taNkVmk+UKVQZuAHIZ6iZc+jNDIN49ikSj0QC+leaaiKIm31V9bA9KrrPHfhXSxeFjTu11IA67l5GODa8mdLflh0AAjRwsNkJzqNp+IJzssb4ryr696AUN5kQXKpXt6ixGFq2cUVNFly816plUrbS68QZNnkIpBF3WZo+CcmRIW+rOW5tGPUNBQtTbLUtBij+Xhu636CFfBl0ylPo0ijGStsnJZyFdC8aLG1cLMh9369ROCrqXUamov32L6IV4gcEHzc3Q3l9VHoOYrkhvMisq8WGbRrbNpCEqYG8T66fcIJ4cwV4ue73rbeKKCS8BAofr6nArah8lpmzmXLgc7Cq02yAnm7OV1In+DbRdm3O87fF+UhZWu0b16BVeouMGl1vXRFodYbqLsdE6ONIrwKsGZRmy11fTsJKl7aNr7EL39ktofAFYGgjmEMdLClbHh2NSf2uhbjVBN3X4pI8X2OUY6DxLzFxUzCyU0BHhbVFomuLzCzenoO+7uISvWEfr8wk+7o9N3H4IKjvLDJEKcb6HKgZ7fP+0qS/98e5K3pMm6Y7wPZDPPgFyLVNo74u2wjytY1wEzZr3H1B61BtagcSWM65lso+h2pjuEjcqWFjyejQHVAOv0vhgx52OiQnl6LQJbds9/mckOoPymsil6HW05AQnVpAqF6xmGsQ6/hEAp
    username: AgCH51/EbsM+9OIyo3DwoIj4S/gJQ/AYB9dWqLvD8wVMmAKS/uU0agi4IuhqzkwiAuRQ1SHmqBuW7oZySs5uiae8SRriKJaUNVW1BuQ2KruxAsYYdbWolhYxyPJ4X3ehM+OH+kz8zja8OTGBFPGWC8tJbkoSxr+iSi+PwIwDRAv/MKPOq9R6aAdynP82fAglqqH0YphAvXpbM/yy//4HCXuhdt2LXzLHjU8jqKqt/envpicb0IIopP31c1fhyol6BPj8SWcNir//aDSTOheyJ04mZoIQiJsjOfAbOM9dzABCA5wv4Th10kutblKmaNhDmvLYJiQbswx8J29nWVMpHro2Ns60vZfa6ZouL0nckJYmRIcAQ0qC735fsQTloCc4vXnLfNAnB8r4Uud83A3ox3CvYCRPPNJW1FBzabobm9J1Hvk50KgMKobUfyKBL4ykLVYrhHZpxwL1CCOeJf4bahtnKsWAun//wTf8Aw9BaAgp4GcLLR3+xQt9vSD8dZ/942r3TAEX5P5bW/Ut7s2vi1ESrJRkfeyzTe4jX9LXaOmQ3kcQ9FSJh3VU/ssWg7Xs1j6PJKmINDAD+sp5OzQ9Os0dleqf9QKoXEw28q5FftSTd02gMtkuqm9zSH4eiC6Tkt9aoIQNHIoIY7PXpyn8iqdjw15XJKllJGF9LL32iC4nMYASSYIm2+Y8DJ5H5Of5AX7mb67RQwKwS0o=
  template:
    metadata:
      name: redis-auth
      namespace: redis-dev
    type: Opaque
