apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.com
spec:
  project: default
  source:
    repoURL: https://github.com/Techtaurant/gitops.git
    targetRevision: HEAD
    path: postgres-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
